# Generated by Django 6.0.2 on 2026-02-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_delete_contentcampaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('scheduled', 'scheduled'), ('published', 'published')], default='draft', max_length=20),
        ),
    ]
